---
- hosts: ubuntu
  user: ansible
  become: true
  vars:
    tomcat_url: "https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.99/bin/apache-tomcat-8.5.99.tar.gz"
    tomcat_version: "apache-tomcat-8.5.99"
    tomcat_dir: "/opt/tomcat"

  tasks:

  - name: Install OpenJDK
    ansible.builtin.apt:
      name: "openjdk-8-jre"
      state: present

  - name: Create Tomcat group
    ansible.builtin.group:
      name: tomcat
      state: present

  - name: Create Tomcat user
    ansible.builtin.user:
      name: tomcat
      group: tomcat
      state: present

  - name: Create Tomcat directory
    ansible.builtin.file:
      path: "{{ tomcat_dir }}"
      state: directory
      mode: '0755'
      owner: tomcat
      group: tomcat
      
  - name: Download Tomcat
    ansible.builtin.unarchive:
      src: "{{ tomcat_url }}"
      dest: "{{ tomcat_dir }}"
      remote_src: true

  - name: Copy downloaded Tomcat to {{ tomcat_dir }}
    ansible.builtin.copy:
      remote_src: true
      src: "{{ tomcat_dir }}/{{ tomcat_version }}/"
      dest: "{{ tomcat_dir }}/"
      owner: "tomcat"
      group: "tomcat"
      directory_mode: '0755'
      mode: '0755'

  - name: Clean Tomcat download
    ansible.builtin.file:
      path: "{{ tomcat_dir }}/{{ tomcat_version }}"
      state: absent

  - name: Copy sample.war
    ansible.builtin.copy:
      src: "./files/sample.war"
      dest: "{{ tomcat_dir }}/webapps/sample.war"
      owner: "tomcat"
      group: "tomcat"
      mode: '0755'
      

  - name: Copy tomcat.service
    ansible.builtin.copy:
      src: ./files/tomcat.service
      dest: /etc/systemd/system/tomcat.service
      mode: '0755'

  - name: Reload systemd
    ansible.builtin.systemd:
      daemon-reload: yes

  - name: Enable the tomcat service and start
    ansible.builtin.systemd:
      name: tomcat
      enabled: yes
      state: started
