---
- hosts: rocky
  user: ansible
  become: true

  tasks:

  - name: Install apache
    ansible.builtin.yum:
      name: httpd
      state: present

  - name: Enable apache
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: true

  - name: Enable firewall ports
    ansible.posix.firewalld:
      port: "{{ item }}"
      permanent: true
      state: enabled
      immediate: true
    loop:
      - "80/tcp"
      - "443/tcp"
      - "8080/tcp"

  - name: Copy proxy conf
    ansible.builtin.copy:
      src: "./files/sample-app.conf"
      dest: "/etc/httpd/conf.d"
      mode: "0744"

  - name: Restart apache service
    ansible.builtin.systemd:
      name: httpd.service
      state: reloaded
