---
- hosts: linux
  user: sysadmin
  become: true
  vars:
    ansible_host_key_checking: false

  tasks:
  
  - name: Create ansible group                                            
    ansible.builtin.group:                                                
      name: ansible                                                                                                             
      state: present 

  - name: Create ansible user                                             
    ansible.builtin.user:                                                
      name: ansible                                                       
      group: ansible                                                      
      state: present 
 
  - name: Give ansible user SUDO privileges without password (DEBIAN)
    ansible.builtin.lineinfile:
      path: /etc/sudoers
      insertafter: "^root"
      line: "ansible ALL=(ALL) NOPASSWD: ALL"
    when: ansible_os_family == "Debian"

  - name: Give ansible user SUDO privileges without password (DEBIAN)
    ansible.builtin.lineinfile:
      path: /etc/sudoers
      insertafter: "^root"
      line: "ansible ALL=(ALL) NOPASSWD: ALL"
    when: ansible_os_family == "RedHat"

  - name: Disable SSH RootLogin on RHEL servers
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin'
      line: "PermitRootLogin no"
    notify: Restart SSH Service
    when: ansible_os_family == "RedHat"

  - name: Disable SSH Password Authentication on RHEL servers
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication'
      line: "PasswordAuthentication no" 
    notify: Restart SSH Service
    when: ansible_os_family == "RedHat"

  - name: Disable SSH RootLogin on Debian servers
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^#PermitRootLogin'
      line: "PermitRootLogin no"
      backrefs: yes
    notify: Restart SSH Service
    when: ansible_os_family == "Debian"

  - name: Disable SSH Password Authentication on Debian servers (default config file)
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^#PasswordAuthentication'
      line: "PasswordAuthentication no"
      backrefs: yes 
    notify: Restart SSH Service
    when: ansible_os_family == "Debian"

  #- name: Check if 50-cloud-init.conf exists on Debian
  #  ansible.builtin.stat:
  #    path: /etc/ssh/sshd_config.d/50-cloud-init.conf
  #  register: stat_result
  #  when: ansible_os_family == "Debian"

  - name: Disable SSH Password Authentication on Debian servers (file under /etc/ssh/sshd_config.d/)
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config.d/50-cloud-init.conf
      regexp: '^PasswordAuthentication'
      line: "#PasswordAuthentication yes"
      backrefs: yes
    when:
    #  - stat_result.stat.exists
      - ansible_os_family == "Debian"
    notify: Restart SSH Service

  handlers:
  
  - name: Restart SSH Service
    ansible.builtin.systemd:
      name: sshd
      state: restarted 
           
