---
- name: Configure Proxy Server
  hosts: rocky
  user: ansible
  become: true

  tasks:

  - name: Install apache
    ansible.builtin.yum:
      name: httpd
      state: present

  - name: Enable apache
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: true

  - name: Enable firewall ports
    ansible.posix.firewalld:
      port: "{{ item }}"
      permanent: true
      state: enabled
      immediate: true
    loop:
      - "80/tcp"
      - "443/tcp"
      - "8080/tcp"

  - name: Allow httpd scripts and modules to connect to the network using TCP
    ansible.builtin.shell: "setsebool -P httpd_can_network_connect on"

  - name: Allow httpd to act as a relay
    ansible.builtin.shell: "setsebool -P httpd_can_network_relay on"

  - name: Copy proxy conf
    ansible.builtin.copy:
      src: "../files/sample-app.conf"
      dest: "/etc/httpd/conf.d"
      mode: "0744"
    notify: Restart httpd service

  - name: Listen on ports 80, 8080 & 443                             
    ansible.builtin.lineinfile:                                          
      path: /etc/httpd/conf/httpd.conf                                         
      regex: '^#Listen'                                         
      line: "Listen 8080\nListen 443"
      backrefs: yes                                         
    notify: Restart httpd service
 
  - name: Load Proxy Modules                             
    ansible.builtin.lineinfile:                                          
      path: /etc/httpd/conf/httpd.conf                                         
      regex: '^# LoadModule'                                         
      line: "LoadModule proxy_module modules/mod_proxy.so\nLoadModule proxy_http_module modules/mod_proxy_http.so"
      backrefs: yes               
    notify: Restart httpd service
 
  handlers:
                       
  - name: Restart httpd service
    ansible.builtin.systemd:
      name: httpd.service
      state: reloaded
